 # Initially selects the ROI(region of interest) coordinates and stores as a dictionary in .yaml
# Finally copy these Coordinates of ROIs and along with the Tracking summary stores in the .yaml file.
# ROI coordinates are are in (x,y) format:   --x then in next line -y co ordinate then in next line new point coordinates. 
---
rois:
  ROI1:
  - - 22.0
    - 46.0
  - - 484.0
    - 62.0
  - - 526.0
    - 453.0
  - - 12.0
    - 435.0
  ROI2:
  - - 72.0
    - 445.0
  - - 533.0
    - 468.0
  - - 565.0
    - 716.0
  - - 18.0
    - 714.0
  ROI3:
  - - 590.0
    - 293.0
  - - 861.0
    - 267.0
  - - 885.0
    - 613.0
  - - 585.0
    - 661.0
objects:
  3:
    class: person
    sessions:
    - roi: ROI3
      enter_time: '00:00:00.016'
      exit_time: '00:00:18.105'
      duration: 18.09
  4:
    class: person
    sessions:
    - roi: ROI2
      enter_time: '00:00:00.016'
      exit_time: '00:00:00.216'
      duration: 0.2
    - roi: ROI2
      enter_time: '00:00:00.233'
      exit_time: '00:00:00.283'
      duration: 0.05
    - roi: ROI1
      enter_time: '00:00:00.550'
      exit_time: '00:00:02.736'
      duration: 2.19
    - roi: ROI1
      enter_time: '00:00:03.103'
      exit_time: '00:00:03.170'
      duration: 0.07
    - roi: ROI2
      enter_time: '00:00:03.270'
      exit_time: '00:00:07.842'
      duration: 4.57
    - roi: ROI2
      enter_time: '00:00:08.293'
      exit_time: '00:00:14.000'
      duration: 5.71
    - roi: ROI1
      enter_time: '00:00:14.000'
      exit_time: '00:00:14.033'
      duration: 0.03
    - roi: ROI2
      enter_time: '00:00:14.033'
      exit_time: '00:00:18.105'
      duration: 4.07
  43:
    class: person
    sessions:
    - roi: ROI3
      enter_time: '00:00:01.885'
      exit_time: '00:00:18.105'
      duration: 16.22
  62:
    class: person
    sessions:
    - roi: ROI3
      enter_time: '00:00:03.637'
      exit_time: '00:00:18.105'
      duration: 14.47
  86:
    class: person
    sessions:
    - roi: ROI3
      enter_time: '00:00:04.288'
      exit_time: '00:00:18.105'
      duration: 13.82
  113:
    class: person
    sessions:
    - roi: ROI3
      enter_time: '00:00:05.122'
      exit_time: '00:00:18.105'
      duration: 12.98
  114:
    class: person
    sessions:
    - roi: ROI3
      enter_time: '00:00:05.122'
      exit_time: '00:00:18.105'
      duration: 12.98
  218:
    class: person
    sessions:
    - roi: ROI3
      enter_time: '00:00:08.493'
      exit_time: '00:00:18.105'
      duration: 9.61
  224:
    class: person
    sessions:
    - roi: ROI1
      enter_time: '00:00:08.627'
      exit_time: '00:00:18.105'
      duration: 9.48
  227:
    class: person
    sessions:
    - roi: ROI1
      enter_time: '00:00:08.727'
      exit_time: '00:00:18.105'
      duration: 9.38
  231:
    class: person
    sessions:
    - roi: ROI1
      enter_time: '00:00:08.793'
      exit_time: '00:00:18.105'
      duration: 9.31
  244:
    class: person
    sessions:
    - roi: ROI3
      enter_time: '00:00:09.111'
      exit_time: '00:00:18.105'
      duration: 8.99
  251:
    class: person
    sessions:
    - roi: ROI1
      enter_time: '00:00:09.377'
      exit_time: '00:00:18.105'
      duration: 8.73
  270:
    class: person
    sessions:
    - roi: ROI3
      enter_time: '00:00:10.696'
      exit_time: '00:00:18.105'
      duration: 7.41
  280:
    class: person
    sessions:
    - roi: ROI1
      enter_time: '00:00:11.780'
      exit_time: '00:00:12.515'
      duration: 0.73
    - roi: ROI1
      enter_time: '00:00:13.182'
      exit_time: '00:00:18.105'
      duration: 4.92
  342:
    class: person
    sessions:
    - roi: ROI2
      enter_time: '00:00:14.500'
      exit_time: '00:00:18.105'
      duration: 3.6
  347:
    class: person
    sessions:
    - roi: ROI1
      enter_time: '00:00:14.600'
      exit_time: '00:00:18.105'
      duration: 3.5
